[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "sindy-shred"
dynamic = ["version"]
dependencies = [
    "torch",
    "scipy",
    "numpy",
]

[project.optional-dependencies]
dev = [
    "black",
    "build",
    "codespell",
    "coverage[toml]",
    "pytest>=6.2.4",
    "ipython",
    "pre-commit",
    "pytest-cov",
    "setuptools_scm",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["sindy_shred"]

[tool.setuptools_scm]
